### ISSUE TITLE
Pin dependency `quiz` version

### ISSUE THREAD

**Issue by ariebovenberg** [mozilla-services/find-package-rugaru#147]
Hi there,

Great to see my library quiz is of use to you! I'd recommend pinning the version for now so you won't get any unexpected surprises if the API changes a little bit.

just specify: `quiz==0.2.0` (current release at this time) in your requirements.

**Comment by g-k** [comment]
Yep, quiz has been great! Thank you! It's pinned in:

https://github.com/mozilla-services/find-package-rugaru/blob/258afa33e2ccf0e0f94cccbb57a25e7ecd251904/requirements.txt.lock#L48-L50

I still need to bump it to 0.2.0.
